name = "lucyandellie-site"
compatibility_date = "2024-01-01"
pages_build_output_dir = "."

[[d1_databases]]
binding = "DB"
database_name = "lucyandellie-notes"
database_id = "a6d13703-237f-42b1-bbb9-5788e83f4965"
